services:
  - type: web
    name: current-chronicle-api
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URLS
        sync: false
      - key: USE_MEMORY_DB
        value: "false"
