services:
  - type: web
    name: current-chronicle
    runtime: node
    buildCommand: cd backend && npm install && cd ../frontend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URLS
        sync: false
      - key: USE_MEMORY_DB
        value: "false"
